export { default as Root } from './Root'
export { ErrorBoundary } from './ErrorBoundary'
export { default as Homepage } from './Homepage'
export { default as CategoryPage } from './CategoryPage'
export { default as ProductPage } from './ProductPage'
export { default as CataloguePage } from './CataloguePage'
export { default as BlogPage } from './BlogPage'
export { default as CartPage } from './CartPage'
export { default as CheckoutPage } from './CheckoutPage'
export { default as ConfirmationPage } from './ConfirmationPage'
